(deftheme base16-eighties
  "Created 2014-08-20.")

(custom-theme-set-faces
 'base16-eighties
 '(fringe ((t (:background "#747369"))))
 '(minibuffer-prompt ((t (:foreground "#6699cc"))))
 '(mode-line ((t (:background "#747369" :foreground "#e8e6df"))))
 '(region ((t (:background "#a09f93"))))
 '(font-lock-comment-face ((t (:foreground "#a09f93"))))
 '(font-lock-constant-face ((t (:foreground "#99cc99"))))
 '(font-lock-doc-string-face ((t (:foreground "#a09f93"))))
 '(font-lock-function-name-face ((t (:foreground "#6699cc"))))
 '(font-lock-keyword-face ((t (:foreground "#cc99cc"))))
 '(font-lock-string-face ((t (:foreground "#99cc99"))))
 '(font-lock-type-face ((t (:foreground "#ffcc66"))))
 '(font-lock-variable-name-face ((t (:foreground "#f2777a"))))
 '(font-lock-warning-face ((t (:foreground "#f2777a"))))
 '(hl-line ((t (:background "#747369"))))
 '(linum ((t (:background "#747369" :foreground "#e8e6df"))))
 '(org-date ((t (:foreground "#cc99cc"))))
 '(org-done ((t (:foreground "#99cc99"))))
 '(org-hide ((t (:foreground "#747369"))))
 '(org-link ((t (:foreground "#6699cc"))))
 '(org-todo ((t (:foreground "#f2777a"))))
 '(show-paren-match ((t (:background "#6699cc" :foreground "#747369"))))
 '(show-paren-mismatch ((t (:background "#f99157" :foreground "#747369"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#cc99cc"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#6699cc"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#66cccc"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#99cc99"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#ffcc66"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#f99157"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#f2777a"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#a09f93"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#e8e6df"))))
 '(default ((t (:background "#393939" :foreground "#e8e6df")))))

(provide-theme 'base16-eighties)
